[package]
name = 'airdash_id'
version = '0.1.0'
edition = '2021'
license = 'MIT'

[dependencies]
proc-bitfield = '0.2.2'
time = { version = "0.3.21", features = ["macros"] }

[features]
default = []
bench = []

# disabled so it doesnt get included in dependents
# [dev-dependencies]
# criterion = '0.3'

[[bench]]
name = 'snowflake_bench'
harness = false
